name: Build and Deploy Container

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: discord-local-ai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -f lib/docker/Dockerfile -t $IMAGE_NAME .

      - name: Save Docker image to tarball
        run: |
          docker save -o ${IMAGE_NAME}.tar $IMAGE_NAME

      - name: Copy image to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "${{ env.IMAGE_NAME }}.tar"
          target: "~/"

      - name: SSH into remote server and deploy container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            echo "Installing Docker if missing..."
            if ! command -v docker &> /dev/null; then
              curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
              sudo usermod -aG docker $USER
              newgrp docker
            fi

            echo "Loading Docker image..."
            docker load -i ~/discord-local-ai.tar

            echo "Creating necessary directories..."
            mkdir -p ~/discord-local-ai/logs
            mkdir -p ~/discord-local-ai/db

            echo "Stopping and removing existing container..."
            docker stop discord-local-ai || true
            docker rm discord-local-ai || true

            echo "Running new container with GPU and volume mounts..."
            docker run -d \
              --name discord-local-ai \
              --restart always \
              --gpus all \
              -e DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }} \
              -v ~/discord-local-ai/logs:/app/logs \
              -v ~/discord-local-ai/db:/app/db \
              discord-local-ai